import React, { useState } from 'react';
import {
  FileText,
  Copy,
  Download,
  Send,
  CheckCircle2,
  AlertTriangle,
  ShieldAlert,
  Building2,
  MapPin,
  Calendar,
  Cpu,
  Loader2,
  ExternalLink,
} from 'lucide-react';
import { PotholeIncident, GeneratedComplaint } from '../../types';
import { useApp } from '../../context/AppContext';
import { formatDate, formatDateTime } from '../../utils/formatters';

interface ComplaintGeneratorProps {
  incident: PotholeIncident;
}

function buildComplaintText(incident: PotholeIncident, complaintId: string): string {
  const warrantyLine = incident.isUnderWarranty
    ? `Responsible Contractor: ${incident.contractorName} (Under Defect Liability Clause 45.2 — repair at ZERO public cost)`
    : `Responsible Authority: ${incident.authorityName}`;

  return `OFFICIAL CIVIC COMPLAINT — CivicPulse AI-Generated Document
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Complaint ID       : ${complaintId}
Incident Code      : ${incident.code}
BBMP Sahaya Ticket : ${incident.sahayaTicketNo}
Generated At       : ${formatDateTime(new Date().toISOString())}

━━ LOCATION ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Road               : ${incident.roadName}
Landmark           : ${incident.landmark}
Ward               : ${incident.wardNumber} — ${incident.wardName}
Zone               : ${incident.zone}
GPS Coordinates    : ${incident.coordinates.lat.toFixed(5)}° N, ${incident.coordinates.lng.toFixed(5)}° E

━━ HAZARD DETAILS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Pothole Severity   : ${incident.severity}
Depth              : ${incident.depthCm} cm
Surface Area       : ${incident.surfaceAreaSqM} m²
Estimated Fill Vol : ${incident.estimatedVolumeLiters} Litres
AI Priority Score  : ${incident.priorityDetails.overallScore}/100
Report Date        : ${formatDate(incident.reportedAt)}
Supporting Reports : ${incident.upvotes} citizen upvotes | ${incident.complaintsCount} formal complaints

━━ ACCOUNTABILITY ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${warrantyLine}
Authority Notified : ${incident.authorityName}

━━ PRIORITY JUSTIFICATION ━━━━━━━━━━━━━━━━━━━━━━━━━━━

${incident.priorityDetails.explanation.map((e, i) => `${i + 1}. ${e}`).join('\n')}

━━ DISCLAIMER ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

⚠ AI-generated — review before submission.
This document was generated by CivicPulse Neural Engine v4.2.
Verify all field details before submitting to official BBMP/PWD channels.
Submission does not constitute a legally binding notice without human review.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by CivicPulse Bengaluru | AI Pothole Intelligence
`;
}

export const ComplaintGenerator: React.FC<ComplaintGeneratorProps> = ({ incident }) => {
  const { addToast } = useApp();
  const [isGenerating, setIsGenerating] = useState(false);
  const [complaint, setComplaint] = useState<GeneratedComplaint | null>(null);
  const [submissionStatus, setSubmissionStatus] = useState<'DRAFT' | 'COPIED' | 'SUBMITTED'>('DRAFT');

  const generateComplaint = async () => {
    setIsGenerating(true);
    await new Promise(r => setTimeout(r, 900));

    const complaintId = `CP-${incident.code.split('-').slice(2).join('-')}-${String(Math.floor(Math.random() * 900) + 100)}`;
    const fullText = buildComplaintText(incident, complaintId);

    const generated: GeneratedComplaint = {
      complaintId,
      incidentCode: incident.code,
      generatedAt: new Date().toISOString(),
      location: `Ward ${incident.wardNumber} (${incident.wardName}), ${incident.zone} Zone`,
      roadName: incident.roadName,
      landmark: incident.landmark,
      severity: incident.severity,
      priorityScore: incident.priorityDetails.overallScore,
      priorityReason: incident.priorityDetails.explanation[0] || '',
      evidenceImages: [incident.images.original, incident.images.detectionOverlay, incident.images.repaired].filter(Boolean) as string[],
      supportingReportsCount: incident.upvotes,
      responsibleAuthority: incident.authorityName,
      responsibleAuthorityEmail: 'ce.roadinfra@bbmp.gov.in',
      contractorName: incident.contractorName,
      contractorRegistration: undefined,
      isUnderWarranty: incident.isUnderWarranty,
      warrantyClause: incident.isUnderWarranty ? 'Defect Liability Clause 45.2 — Karnataka PWD DLP' : undefined,
      submissionStatus: 'DRAFT',
      aiDisclaimer: 'AI-generated — review before submission',
      fullText,
    };

    setComplaint(generated);
    setSubmissionStatus('DRAFT');
    setIsGenerating(false);
    addToast('Complaint Generated', `${complaintId} ready for review`, 'success');
  };

  const handleCopy = async () => {
    if (!complaint) return;
    try {
      await navigator.clipboard.writeText(complaint.fullText);
      setSubmissionStatus('COPIED');
      addToast('Complaint Copied', 'Text copied to clipboard', 'success');
    } catch {
      addToast('Copy Failed', 'Please select and copy the text manually', 'error');
    }
  };

  const handleDownload = () => {
    if (!complaint) return;
    const blob = new Blob([complaint.fullText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${complaint.complaintId}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    addToast('Evidence Downloaded', `${complaint.complaintId}.txt saved`, 'info');
  };

  const handleMarkSubmitted = () => {
    if (!complaint) return;
    setSubmissionStatus('SUBMITTED');
    setComplaint(prev => prev ? { ...prev, submissionStatus: 'SUBMITTED', submittedAt: new Date().toISOString() } : prev);
    addToast('Marked as Submitted', 'Status updated. Keep your complaint ID for tracking.', 'success');
  };

  return (
    <div className="bg-white brut overflow-hidden">
      {/* Header */}
      <div className="p-4 border-b-2 border-[#121210] flex items-center justify-between bg-[#CFE8D6]/30">
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 bg-white border-2 border-[#121210] flex items-center justify-center">
            <FileText className="w-4 h-4 text-[#121210]" />
          </div>
          <div>
            <h3 className="font-display text-sm font-black text-[#121210] uppercase">Generate Official Grievance</h3>
            <p className="text-[11px] text-[#4A4A46] font-mono">Structured complaint notice with audited evidence</p>
          </div>
        </div>
        {complaint && (
          <span className={`stamp text-[10px] font-black ${
            submissionStatus === 'SUBMITTED'
              ? 'border-[#2E8C42] text-[#2E8C42]'
              : submissionStatus === 'COPIED'
              ? 'border-[#121210] text-[#121210]'
              : 'border-[#E8A030] text-[#E8A030]'
          }`}>
            {submissionStatus === 'SUBMITTED' ? 'SUBMITTED' : submissionStatus === 'COPIED' ? 'COPIED' : 'DRAFT'}
          </span>
        )}
      </div>

      <div className="p-5 space-y-4">
        {!complaint ? (
          <div className="space-y-4">
            <div className="grid grid-cols-2 gap-3 text-xs">
              {[
                { icon: FileText, label: 'COMPLAINT ID', value: 'Auto-generated' },
                { icon: MapPin, label: 'LOCATION', value: `Ward ${incident.wardNumber}` },
                { icon: AlertTriangle, label: 'SEVERITY', value: incident.severity },
                { icon: Cpu, label: 'PRIORITY SCORE', value: `${incident.priorityDetails.overallScore}/100` },
                { icon: Building2, label: 'AUTHORITY', value: incident.authorityName.split(' ').slice(0, 2).join(' ') },
                { icon: Calendar, label: 'EVIDENCE IMAGES', value: `${Object.values(incident.images).filter(Boolean).length} attached` },
              ].map(({ icon: Icon, label, value }) => (
                <div key={label} className="flex items-center gap-2.5 p-2.5 bg-[#CFE8D6]/30 border-2 border-[#121210]">
                  <Icon className="w-3.5 h-3.5 text-[#121210] flex-shrink-0" />
                  <div>
                    <div className="text-[10px] text-[#4A4A46] font-mono font-bold uppercase">{label}</div>
                    <div className="text-[#121210] font-black">{value}</div>
                  </div>
                </div>
              ))}
            </div>

            {incident.isUnderWarranty && (
              <div className="p-3 bg-[#CFE8D6]/50 border-2 border-[#121210] flex items-start gap-2.5 text-xs">
                <ShieldAlert className="w-4 h-4 text-[#2E8C42] flex-shrink-0 mt-0.5" />
                <div>
                  <div className="font-display font-black text-[#121210]">Warranty Clause 45.2 Active</div>
                  <p className="font-body text-[#4A4A46] mt-0.5">
                    Repair must be completed at ZERO public cost by {incident.contractorName} under PWD Defect Liability terms.
                  </p>
                </div>
              </div>
            )}

            <div className="p-3 bg-[#E8A030]/20 border-2 border-[#121210] flex items-start gap-2.5 text-xs font-mono text-[#121210]">
              <AlertTriangle className="w-4 h-4 text-[#121210] flex-shrink-0 mt-0.5" />
              <span>AI-generated draft notice — audit details before submission to BBMP Sahaya.</span>
            </div>

            <button
              onClick={generateComplaint}
              disabled={isGenerating}
              className="w-full py-3 bg-[#121210] text-[#CFE8D6] hover:bg-[#2E8C42] hover:text-white brut font-display font-black text-xs uppercase tracking-wider flex items-center justify-center gap-2 btn-press transition-all disabled:opacity-60 cursor-pointer"
            >
              {isGenerating ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  <span>Generating Legal Notice...</span>
                </>
              ) : (
                <>
                  <FileText className="w-4 h-4" />
                  <span>Generate Official Grievance Notice</span>
                </>
              )}
            </button>
          </div>
        ) : (
          <div className="space-y-4">
            <div className="p-4 bg-[#CFE8D6]/30 border-2 border-[#121210] space-y-3">
              <div className="flex items-center justify-between">
                <div className="font-mono text-xs font-black text-[#121210]">{complaint.complaintId}</div>
                <span className={`tag font-mono text-[10px] font-bold ${
                  complaint.severity === 'CRITICAL' ? 'bg-[#C03A3A] text-white' : 'bg-[#E8A030] text-[#121210]'
                }`}>
                  {complaint.severity}
                </span>
              </div>

              <div className="grid grid-cols-2 gap-x-4 gap-y-2 text-xs font-mono">
                <div>
                  <div className="text-[10px] text-[#4A4A46] uppercase font-bold">LOCATION</div>
                  <div className="text-[#121210] font-bold">{complaint.location}</div>
                </div>
                <div>
                  <div className="text-[10px] text-[#4A4A46] uppercase font-bold">PRIORITY SCORE</div>
                  <div className="text-[#2E8C42] font-black">{complaint.priorityScore}/100</div>
                </div>
                <div>
                  <div className="text-[10px] text-[#4A4A46] uppercase font-bold">AUTHORITY</div>
                  <div className="text-[#121210] font-bold">{complaint.responsibleAuthority}</div>
                </div>
                <div>
                  <div className="text-[10px] text-[#4A4A46] uppercase font-bold">SUPPORTING REPORTS</div>
                  <div className="text-[#121210] font-bold">{complaint.supportingReportsCount} upvotes</div>
                </div>
                {complaint.contractorName && (
                  <div className="col-span-2">
                    <div className="text-[10px] text-[#4A4A46] uppercase font-bold">
                      {complaint.isUnderWarranty ? 'CONTRACTOR (WARRANTY ACTIVE)' : 'PREVIOUS CONTRACTOR'}
                    </div>
                    <div className="text-[#121210] font-bold">{complaint.contractorName}</div>
                    {complaint.warrantyClause && (
                      <div className="text-[10px] text-[#2E8C42] font-bold mt-0.5">{complaint.warrantyClause}</div>
                    )}
                  </div>
                )}
              </div>
            </div>

            {/* Full complaint text in brutalist document box */}
            <div className="border-2 border-[#121210] bg-white overflow-hidden">
              <div className="flex items-center justify-between px-3 py-2 border-b-2 border-[#121210] bg-[#CFE8D6]/40">
                <span className="text-[10px] font-mono font-bold text-[#121210] uppercase tracking-wider">Complaint Notice Document</span>
                <ExternalLink className="w-3.5 h-3.5 text-[#121210]" />
              </div>
              <pre className="p-4 text-[11px] text-[#121210] font-mono leading-relaxed whitespace-pre-wrap overflow-auto max-h-48">
                {complaint.fullText}
              </pre>
            </div>

            {/* AI disclaimer */}
            <div className="p-2.5 bg-[#E8A030]/20 border-2 border-[#121210] flex items-center gap-2 text-[10px] text-[#121210] font-mono font-bold">
              <AlertTriangle className="w-3.5 h-3.5 flex-shrink-0" />
              <span>{complaint.aiDisclaimer}</span>
            </div>

            {/* Action buttons */}
            <div className="grid grid-cols-3 gap-2">
              <button
                onClick={handleCopy}
                className="flex items-center justify-center gap-1.5 py-2.5 bg-white hover:bg-[#CFE8D6] brut-sm text-xs font-mono font-bold text-[#121210] transition-all cursor-pointer"
              >
                <Copy className="w-3.5 h-3.5" />
                <span>Copy</span>
              </button>
              <button
                onClick={handleDownload}
                className="flex items-center justify-center gap-1.5 py-2.5 bg-white hover:bg-[#CFE8D6] brut-sm text-xs font-mono font-bold text-[#121210] transition-all cursor-pointer"
              >
                <Download className="w-3.5 h-3.5" />
                <span>Download</span>
              </button>
              {submissionStatus !== 'SUBMITTED' ? (
                <button
                  onClick={handleMarkSubmitted}
                  className="flex items-center justify-center gap-1.5 py-2.5 bg-[#2E8C42] hover:bg-[#121210] text-white hover:text-[#CFE8D6] brut-sm text-xs font-mono font-bold transition-all cursor-pointer btn-press"
                >
                  <Send className="w-3.5 h-3.5" />
                  <span>Submit</span>
                </button>
              ) : (
                <div className="flex items-center justify-center gap-1.5 py-2.5 bg-[#CFE8D6] border-2 border-[#121210] text-xs font-mono font-black text-[#2E8C42]">
                  <CheckCircle2 className="w-3.5 h-3.5" />
                  <span>Submitted</span>
                </div>
              )}
            </div>

            {/* Regenerate */}
            <button
              onClick={() => setComplaint(null)}
              className="w-full text-center text-xs text-[#121210] hover:underline font-mono font-bold cursor-pointer"
            >
              ← Regenerate notice
            </button>
          </div>
        )}
      </div>
    </div>
  );
};
