import React, { useState } from 'react';
import {
  FileText,
  Copy,
  Download,
  Send,
  CheckCircle2,
  AlertTriangle,
  ShieldAlert,
  Building2,
  MapPin,
  Calendar,
  Cpu,
  Loader2,
  ExternalLink,
} from 'lucide-react';
import { PotholeIncident, GeneratedComplaint } from '../../types';
import { useApp } from '../../context/AppContext';
import { formatDate, formatDateTime } from '../../utils/formatters';

interface ComplaintGeneratorProps {
  incident: PotholeIncident;
}

function buildComplaintText(incident: PotholeIncident, complaintId: string): string {
  const warrantyLine = incident.isUnderWarranty
    ? `Responsible Contractor: ${incident.contractorName} (Under Defect Liability Clause 45.2 — repair at ZERO public cost)`
    : `Responsible Authority: ${incident.authorityName}`;

  return `OFFICIAL CIVIC COMPLAINT — CivicPulse AI-Generated Document
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Complaint ID       : ${complaintId}
Incident Code      : ${incident.code}
BBMP Sahaya Ticket : ${incident.sahayaTicketNo}
Generated At       : ${formatDateTime(new Date().toISOString())}

━━ LOCATION ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Road               : ${incident.roadName}
Landmark           : ${incident.landmark}
Ward               : ${incident.wardNumber} — ${incident.wardName}
Zone               : ${incident.zone}
GPS Coordinates    : ${incident.coordinates.lat.toFixed(5)}° N, ${incident.coordinates.lng.toFixed(5)}° E

━━ HAZARD DETAILS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Pothole Severity   : ${incident.severity}
Depth              : ${incident.depthCm} cm
Surface Area       : ${incident.surfaceAreaSqM} m²
Estimated Fill Vol : ${incident.estimatedVolumeLiters} Litres
AI Priority Score  : ${incident.priorityDetails.overallScore}/100
Report Date        : ${formatDate(incident.reportedAt)}
Supporting Reports : ${incident.upvotes} citizen upvotes | ${incident.complaintsCount} formal complaints

━━ ACCOUNTABILITY ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${warrantyLine}
Authority Notified : ${incident.authorityName}

━━ PRIORITY JUSTIFICATION ━━━━━━━━━━━━━━━━━━━━━━━━━━━

${incident.priorityDetails.explanation.map((e, i) => `${i + 1}. ${e}`).join('\n')}

━━ DISCLAIMER ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

⚠ AI-generated — review before submission.
This document was generated by CivicPulse Neural Engine v4.2.
Verify all field details before submitting to official BBMP/PWD channels.
Submission does not constitute a legally binding notice without human review.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by CivicPulse Bengaluru | AI Pothole Intelligence
`;
}

export const ComplaintGenerator: React.FC<ComplaintGeneratorProps> = ({ incident }) => {
  const { addToast } = useApp();
  const [isGenerating, setIsGenerating] = useState(false);
  const [complaint, setComplaint] = useState<GeneratedComplaint | null>(null);
  const [submissionStatus, setSubmissionStatus] = useState<'DRAFT' | 'COPIED' | 'SUBMITTED'>('DRAFT');

  const generateComplaint = async () => {
    setIsGenerating(true);
    await new Promise(r => setTimeout(r, 1200));

    const complaintId = `CP-${incident.code.split('-').slice(2).join('-')}-${String(Math.floor(Math.random() * 900) + 100)}`;
    const fullText = buildComplaintText(incident, complaintId);

    const generated: GeneratedComplaint = {
      complaintId,
      incidentCode: incident.code,
      generatedAt: new Date().toISOString(),
      location: `Ward ${incident.wardNumber} (${incident.wardName}), ${incident.zone} Zone`,
      roadName: incident.roadName,
      landmark: incident.landmark,
      severity: incident.severity,
      priorityScore: incident.priorityDetails.overallScore,
      priorityReason: incident.priorityDetails.explanation[0] || '',
      evidenceImages: [incident.images.original, incident.images.detectionOverlay, incident.images.repaired].filter(Boolean) as string[],
      supportingReportsCount: incident.upvotes,
      responsibleAuthority: incident.authorityName,
      responsibleAuthorityEmail: 'ce.roadinfra@bbmp.gov.in',
      contractorName: incident.contractorName,
      contractorRegistration: undefined,
      isUnderWarranty: incident.isUnderWarranty,
      warrantyClause: incident.isUnderWarranty ? 'Defect Liability Clause 45.2 — Karnataka PWD DLP' : undefined,
      submissionStatus: 'DRAFT',
      aiDisclaimer: 'AI-generated — review before submission',
      fullText,
    };

    setComplaint(generated);
    setSubmissionStatus('DRAFT');
    setIsGenerating(false);
    addToast('Complaint Generated', `${complaintId} ready for review`, 'success');
  };

  const handleCopy = async () => {
    if (!complaint) return;
    try {
      await navigator.clipboard.writeText(complaint.fullText);
      setSubmissionStatus('COPIED');
      addToast('Complaint Copied', 'Text copied to clipboard', 'success');
    } catch {
      addToast('Copy Failed', 'Please select and copy the text manually', 'error');
    }
  };

  const handleDownload = () => {
    if (!complaint) return;
    const blob = new Blob([complaint.fullText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${complaint.complaintId}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    addToast('Evidence Downloaded', `${complaint.complaintId}.txt saved`, 'info');
  };

  const handleMarkSubmitted = () => {
    if (!complaint) return;
    setSubmissionStatus('SUBMITTED');
    setComplaint(prev => prev ? { ...prev, submissionStatus: 'SUBMITTED', submittedAt: new Date().toISOString() } : prev);
    addToast('Marked as Submitted', 'Status updated. Keep your complaint ID for tracking.', 'success');
  };

  const severityColor = {
    CRITICAL: 'text-red-400 bg-red-500/10 border-red-500/30',
    HIGH: 'text-amber-400 bg-amber-500/10 border-amber-500/30',
    MEDIUM: 'text-yellow-400 bg-yellow-500/10 border-yellow-500/30',
    LOW: 'text-cyan-400 bg-cyan-500/10 border-cyan-500/30',
  }[incident.severity];

  return (
    <div className="rounded-2xl border border-white/10 bg-[#090C16] overflow-hidden">
      {/* Header */}
      <div className="p-5 border-b border-white/10 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 rounded-xl bg-amber-500/10 border border-amber-500/30 flex items-center justify-center">
            <FileText className="w-4 h-4 text-amber-400" />
          </div>
          <div>
            <h3 className="font-mono text-sm font-bold text-white">Generate Official Complaint</h3>
            <p className="text-[11px] text-slate-400 mt-0.5">Structured complaint document with all evidence</p>
          </div>
        </div>
        {complaint && (
          <span className={`text-[10px] font-mono font-bold px-2.5 py-1 rounded-full border ${
            submissionStatus === 'SUBMITTED'
              ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30'
              : submissionStatus === 'COPIED'
              ? 'bg-blue-500/10 text-blue-400 border-blue-500/30'
              : 'bg-amber-500/10 text-amber-400 border-amber-500/30'
          }`}>
            {submissionStatus === 'SUBMITTED' ? '✓ SUBMITTED' : submissionStatus === 'COPIED' ? 'COPIED' : 'DRAFT'}
          </span>
        )}
      </div>

      <div className="p-5 space-y-5">
        {!complaint ? (
          /* Pre-generation preview */
          <div className="space-y-4">
            {/* What will be included */}
            <div className="grid grid-cols-2 gap-3 text-xs">
              {[
                { icon: FileText, label: 'Complaint ID', value: 'Auto-generated' },
                { icon: MapPin, label: 'Location', value: `Ward ${incident.wardNumber}` },
                { icon: AlertTriangle, label: 'Severity', value: incident.severity },
                { icon: Cpu, label: 'Priority Score', value: `${incident.priorityDetails.overallScore}/100` },
                { icon: Building2, label: 'Authority', value: incident.authorityName.split(' ').slice(0, 2).join(' ') },
                { icon: Calendar, label: 'Evidence Images', value: `${Object.values(incident.images).filter(Boolean).length} attached` },
              ].map(({ icon: Icon, label, value }) => (
                <div key={label} className="flex items-center gap-2.5 p-2.5 rounded-xl bg-white/[0.02] border border-white/5">
                  <Icon className="w-3.5 h-3.5 text-cyan-400 flex-shrink-0" />
                  <div>
                    <div className="text-[10px] text-slate-500 font-mono">{label}</div>
                    <div className="text-slate-200 font-semibold">{value}</div>
                  </div>
                </div>
              ))}
            </div>

            {incident.isUnderWarranty && (
              <div className="p-3 rounded-xl bg-emerald-950/20 border border-emerald-500/30 flex items-start gap-2.5 text-xs">
                <ShieldAlert className="w-4 h-4 text-emerald-400 flex-shrink-0 mt-0.5" />
                <div>
                  <div className="font-bold text-emerald-300">Warranty clause will be cited</div>
                  <p className="text-slate-400 mt-0.5">
                    Defect Liability Clause 45.2 will be included — repair must be done at ZERO public cost by {incident.contractorName}.
                  </p>
                </div>
              </div>
            )}

            <div className="p-3 rounded-xl bg-amber-950/20 border border-amber-500/30 flex items-start gap-2.5 text-xs">
              <AlertTriangle className="w-3.5 h-3.5 text-amber-400 flex-shrink-0 mt-0.5" />
              <span className="text-amber-200/80 italic">AI-generated — review before submission</span>
            </div>

            <button
              onClick={generateComplaint}
              disabled={isGenerating}
              className="w-full py-3 rounded-xl bg-gradient-to-r from-amber-500 to-orange-500 hover:from-amber-400 hover:to-orange-400 text-slate-950 font-bold text-sm flex items-center justify-center gap-2 shadow-[0_0_20px_rgba(245,158,11,0.3)] transition-all hover:scale-[1.01] active:scale-[0.99] disabled:opacity-60 cursor-pointer"
            >
              {isGenerating ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  <span>Generating Complaint...</span>
                </>
              ) : (
                <>
                  <FileText className="w-4 h-4" />
                  <span>Generate Official Complaint</span>
                </>
              )}
            </button>
          </div>
        ) : (
          /* Generated complaint view */
          <div className="space-y-4">
            {/* Complaint header card */}
            <div className="p-4 rounded-xl bg-white/[0.02] border border-white/10 space-y-3">
              <div className="flex items-center justify-between">
                <div className="font-mono text-xs font-extrabold text-white">{complaint.complaintId}</div>
                <span className={`px-2 py-0.5 rounded font-mono text-[10px] font-bold border ${severityColor}`}>
                  {complaint.severity}
                </span>
              </div>

              <div className="grid grid-cols-2 gap-x-4 gap-y-2 text-xs">
                <div>
                  <div className="text-[10px] font-mono text-slate-500">LOCATION</div>
                  <div className="text-slate-200">{complaint.location}</div>
                </div>
                <div>
                  <div className="text-[10px] font-mono text-slate-500">PRIORITY SCORE</div>
                  <div className="text-cyan-400 font-bold">{complaint.priorityScore}/100</div>
                </div>
                <div>
                  <div className="text-[10px] font-mono text-slate-500">AUTHORITY</div>
                  <div className="text-slate-200">{complaint.responsibleAuthority}</div>
                </div>
                <div>
                  <div className="text-[10px] font-mono text-slate-500">SUPPORTING REPORTS</div>
                  <div className="text-amber-300 font-bold">{complaint.supportingReportsCount} upvotes</div>
                </div>
                {complaint.contractorName && (
                  <div className="col-span-2">
                    <div className="text-[10px] font-mono text-slate-500">
                      {complaint.isUnderWarranty ? 'CONTRACTOR (WARRANTY ACTIVE)' : 'PREVIOUS CONTRACTOR'}
                    </div>
                    <div className="text-slate-200">{complaint.contractorName}</div>
                    {complaint.warrantyClause && (
                      <div className="text-[10px] text-emerald-400 mt-0.5">{complaint.warrantyClause}</div>
                    )}
                  </div>
                )}
              </div>
            </div>

            {/* Full complaint text */}
            <div className="rounded-xl border border-white/10 bg-black/30 overflow-hidden">
              <div className="flex items-center justify-between px-3 py-2 border-b border-white/5 bg-white/[0.02]">
                <span className="text-[10px] font-mono text-slate-400 uppercase tracking-wider">Complaint Document</span>
                <ExternalLink className="w-3 h-3 text-slate-500" />
              </div>
              <pre className="p-4 text-[10px] text-slate-300 font-mono leading-relaxed whitespace-pre-wrap overflow-auto max-h-48 scrollbar-thin">
                {complaint.fullText}
              </pre>
            </div>

            {/* AI disclaimer */}
            <div className="p-2.5 rounded-lg bg-amber-950/20 border border-amber-500/20 flex items-center gap-2 text-[10px] text-amber-300 font-mono">
              <AlertTriangle className="w-3 h-3 flex-shrink-0" />
              <span>{complaint.aiDisclaimer}</span>
            </div>

            {/* Action buttons */}
            <div className="grid grid-cols-3 gap-2">
              <button
                onClick={handleCopy}
                className="flex items-center justify-center gap-1.5 py-2.5 rounded-xl bg-white/[0.04] hover:bg-white/[0.08] border border-white/10 text-xs font-semibold text-slate-200 transition-all cursor-pointer"
              >
                <Copy className="w-3.5 h-3.5 text-cyan-400" />
                <span>Copy</span>
              </button>
              <button
                onClick={handleDownload}
                className="flex items-center justify-center gap-1.5 py-2.5 rounded-xl bg-white/[0.04] hover:bg-white/[0.08] border border-white/10 text-xs font-semibold text-slate-200 transition-all cursor-pointer"
              >
                <Download className="w-3.5 h-3.5 text-blue-400" />
                <span>Download</span>
              </button>
              {submissionStatus !== 'SUBMITTED' ? (
                <button
                  onClick={handleMarkSubmitted}
                  className="flex items-center justify-center gap-1.5 py-2.5 rounded-xl bg-emerald-500/10 hover:bg-emerald-500/20 border border-emerald-500/30 text-xs font-bold text-emerald-400 transition-all cursor-pointer"
                >
                  <Send className="w-3.5 h-3.5" />
                  <span>Submit</span>
                </button>
              ) : (
                <div className="flex items-center justify-center gap-1.5 py-2.5 rounded-xl bg-emerald-500/15 border border-emerald-500/40 text-xs font-bold text-emerald-400">
                  <CheckCircle2 className="w-3.5 h-3.5" />
                  <span>Submitted</span>
                </div>
              )}
            </div>

            {/* Regenerate */}
            <button
              onClick={() => setComplaint(null)}
              className="w-full text-center text-[11px] text-slate-500 hover:text-slate-300 transition-colors font-mono cursor-pointer"
            >
              ← Regenerate complaint
            </button>
          </div>
        )}
      </div>
    </div>
  );
};
